<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../eShopLegacy.Utilities/eShopLegacy.Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="App_Start\**\*.cs" />
    <Compile Remove="Global.asax.cs" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <Compile Remove="Migrations\**\*.cs" />
  </ItemGroup>
</Project>