<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>eShopLegacy.Utilities</AssemblyTitle>
    <Product>eShopLegacy.Utilities</Product>
    <Copyright>Copyright ©  2021</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="App_Start\**\*.cs" />
    <Compile Remove="Global.asax.cs" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <Compile Remove="Migrations\**\*.cs" />
  </ItemGroup>
</Project>